// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Feliz.MaterialUI.MaterialTable")>]
[<assembly: AssemblyProductAttribute("Feliz.MaterialUI.MaterialTable")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings written in the Feliz-style for material-table")>]
[<assembly: AssemblyVersionAttribute("1.6.0")>]
[<assembly: AssemblyFileVersionAttribute("1.6.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Feliz.MaterialUI.MaterialTable.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Feliz.MaterialUI.MaterialTable"
    let [<Literal>] AssemblyProduct = "Feliz.MaterialUI.MaterialTable"
    let [<Literal>] AssemblyDescription = "Fable bindings written in the Feliz-style for material-table"
    let [<Literal>] AssemblyVersion = "1.6.0"
    let [<Literal>] AssemblyFileVersion = "1.6.0"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Feliz.MaterialUI.MaterialTable.Tests"
